### ISSUE TITLE
Inconsistent parameters in genesis toml files

### ISSUE THREAD

**Issue by mariari** [anoma/namada#1048]
Currently all end to end tests pass, however there is a configuration error with the: [e2e-tests-single-node.toml](https://github.com/anoma/namada/blob/main/genesis/e2e-tests-single-node.toml), in that the `Dot` token is incorrectly setup

```toml

[token.DOT]
address = "atest1v4ehgw36gg6nvs2zgfpyxsfjgc65yv6pxy6nwwfsxgungdzrggeyzv35gveyxsjyxymyz335hur2jn"
vp = "vp_token"
[token.Dot.balances]
Albert = 1000000
Bertha = 1000000
Christel = 1000000
Daewon = 1000000
faucet = 9223372036854
```

causing two tokens `Dot` and `DOT` to be created
