### ISSUE TITLE
Specify appropriate version(s) of Tendermint in a machine readable format in the repo

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#153]
We should specify at least one Tendermint version we are definitely compatible in our repo in a machine friendly way. Then given any commit of namada, it should be easy to see a version of tendermint that can definitely be used. This could be a simple `tendermint-version` file that simply has a tag/ref of the Tendermint version we are using by default, or something more advanced like a `.toml` that specifies the versions to be used with different feature flags.

e.g. in `eth-bridge-integration`
```toml
[default]
git = "https://github.com/tendermint/tendermint.git"  # default
ref = "v0.37.0-alpha.2"
cargo_default_features = true  # default
cargo_extra_features = []  # default

[abcipp]
git = "https://github.com/heliaxdev/tendermint.git"
ref = "v0.1.1-abcipp"
cargo_default_features = false
cargo_extra_features = [ "abcipp" ]
```

e.g. in `main` (until that also switches to v0.37)
```toml
[default]
git = "https://github.com/heliaxdev/tendermint.git"
ref = "v0.1.1-abcipp"
```
