### ISSUE TITLE
Environment variables don't set the proper values to cometbft config

### ISSUE THREAD

**Issue by qezz** [anoma/namada#1601]
We are trying to do this

```
NAMADA_LEDGER__COMETBFT__INSTRUMENTATION_PROMETHEUS=true
NAMADA_LEDGER__COMETBFT__INSTRUMENTATION_PROMETHEUS_LISTEN_ADDR=0.0.0.0:26661
```

But it doesn't work.
We managed to make it work with modifications to the config file itself `public-testnet-9.0.5aa315d1a22/config.toml`

```console
public-testnet-9.0.5aa315d1a22# cat config.toml | grep -A10 instrumen
```
```toml
[ledger.cometbft.instrumentation]
prometheus = true
prometheus_listen_addr = "0.0.0.0:26661"
max_open_connections = 3
namespace = "cometbft"
```

But it's not convenient to modify the config with every new testnet.
