### ISSUE TITLE
Namada dev build uses MockTxProver

### ISSUE THREAD

**Issue by mateuszjasiuk** [anoma/namada#3950]
Building namada with `make build` (dev build) sets the "testing" feature flag for couple of crates.
```toml
# crates/token/Cargo.toml
[dev-dependencies]
namada_core = { path = "../core", features = ["testing"] }
namada_shielded_token = { path = "../shielded_token", features = ["testing"] }
```
Because of that `MockTxProver` is used for shielded transfers which makes all the txs to pass.
```rs
// shielded_token/src/masp/shielded_wallet.rs
        #[cfg(not(feature = "testing"))]
        let prover = self.utils.local_tx_prover();
        #[cfg(feature = "testing")]
        let prover = testing::MockTxProver(std::sync::Mutex::new(OsRng));
```
