### ISSUE TITLE
Add a per-chain config section for the Ethereum bridge

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#416]
There are various settings validators may want to configure to do with the Ethereum bridge, we should have a configuration section for them. In `config.toml`, this might look something like

```toml
[ledger.ethereum]
oracle_rpc_endpoint = "127.0.0.1:8585"
```
